// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIiYHY1zEUTMutRpAZHGp5k_Rnrw1p72c',
    appId: '1:1051617584787:web:cac9d426bd17b0f8c78f66',
    messagingSenderId: '1051617584787',
    projectId: 'cmsc23-project-149f1',
    authDomain: 'cmsc23-project-149f1.firebaseapp.com',
    storageBucket: 'cmsc23-project-149f1.appspot.com',
    measurementId: 'G-MJ4WKBK60F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1B54V3mLYpnQ9npNPIZDR8afpfUV8Srw',
    appId: '1:1051617584787:android:583855613235989cc78f66',
    messagingSenderId: '1051617584787',
    projectId: 'cmsc23-project-149f1',
    storageBucket: 'cmsc23-project-149f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRJGXWg1PUSqvKH_XFFWqKxtA8RRsPOvw',
    appId: '1:1051617584787:ios:010bbd8009cf79f5c78f66',
    messagingSenderId: '1051617584787',
    projectId: 'cmsc23-project-149f1',
    storageBucket: 'cmsc23-project-149f1.appspot.com',
    iosBundleId: 'com.example.cmsc23proj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRJGXWg1PUSqvKH_XFFWqKxtA8RRsPOvw',
    appId: '1:1051617584787:ios:010bbd8009cf79f5c78f66',
    messagingSenderId: '1051617584787',
    projectId: 'cmsc23-project-149f1',
    storageBucket: 'cmsc23-project-149f1.appspot.com',
    iosBundleId: 'com.example.cmsc23proj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIiYHY1zEUTMutRpAZHGp5k_Rnrw1p72c',
    appId: '1:1051617584787:web:992bfd4855755913c78f66',
    messagingSenderId: '1051617584787',
    projectId: 'cmsc23-project-149f1',
    authDomain: 'cmsc23-project-149f1.firebaseapp.com',
    storageBucket: 'cmsc23-project-149f1.appspot.com',
    measurementId: 'G-DGQF6H7FN5',
  );

}