// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPiwqpbmWYNAlTyrvu_JlEaN8ev5mamls',
    appId: '1:578454353153:web:67d8b1846c98dba99cd700',
    messagingSenderId: '578454353153',
    projectId: 'cmsc23-project-mohadi',
    authDomain: 'cmsc23-project-mohadi.firebaseapp.com',
    storageBucket: 'cmsc23-project-mohadi.appspot.com',
    measurementId: 'G-0PCERNGQHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCk1iL00O6vRsOeQN0i1rUIwc2iZJMY-s',
    appId: '1:578454353153:android:41572ca2ad0358739cd700',
    messagingSenderId: '578454353153',
    projectId: 'cmsc23-project-mohadi',
    storageBucket: 'cmsc23-project-mohadi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVfmE2ZB7mGXsCTUSe6MeiezlforbYHkg',
    appId: '1:578454353153:ios:59b9e99df95c83d89cd700',
    messagingSenderId: '578454353153',
    projectId: 'cmsc23-project-mohadi',
    storageBucket: 'cmsc23-project-mohadi.appspot.com',
    iosBundleId: 'com.example.cmsc23proj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVfmE2ZB7mGXsCTUSe6MeiezlforbYHkg',
    appId: '1:578454353153:ios:59b9e99df95c83d89cd700',
    messagingSenderId: '578454353153',
    projectId: 'cmsc23-project-mohadi',
    storageBucket: 'cmsc23-project-mohadi.appspot.com',
    iosBundleId: 'com.example.cmsc23proj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPiwqpbmWYNAlTyrvu_JlEaN8ev5mamls',
    appId: '1:578454353153:web:8fc249b4fce3bc079cd700',
    messagingSenderId: '578454353153',
    projectId: 'cmsc23-project-mohadi',
    authDomain: 'cmsc23-project-mohadi.firebaseapp.com',
    storageBucket: 'cmsc23-project-mohadi.appspot.com',
    measurementId: 'G-LZZTV6FCY9',
  );

}